### ISSUE TITLE
TF-IDF + negative matrix entries (only KNN_cosine methods)

### ISSUE THREAD

**Issue by duncanmcelfresh** [naszilla/reczilla#11]
only appears to occur with `Jester2Reader` and `AnimeReader` datasets

```
Traceback (most recent call last):
  File "/home/shared/reczilla/RecSys2019_DeepLearning_Evaluation/ParameterTuning/SearchAbstractClass.py", line 400, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/home/shared/reczilla/RecSys2019_DeepLearning_Evaluation/ParameterTuning/RandomSearch.py", line 42, in _evaluate_on_validation
    current_fit_parameters
  File "/home/shared/reczilla/RecSys2019_DeepLearning_Evaluation/ParameterTuning/SearchAbstractClass.py", line 292, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/home/shared/reczilla/RecSys2019_DeepLearning_Evaluation/ParameterTuning/SearchAbstractClass.py", line 282, in _fit_model
    **current_fit_parameters)
  File "/home/shared/reczilla/RecSys2019_DeepLearning_Evaluation/KNN/ItemKNNCFRecommender.py", line 47, in fit
    self.URM_train = TF_IDF(self.URM_train.T).T
  File "/home/shared/reczilla/RecSys2019_DeepLearning_Evaluation/Base/IR_feature_weighting.py", line 66, in TF_IDF
    "TF_IDF: Data matrix contains {} negative values, computing the square root is not possible.".format(np.sum(dataMatrix.data < 0.0))
AssertionError: TF_IDF: Data matrix contains 1452209 negative values, computing the square root is not possible.
```

**Comment by duncanmcelfresh** [comment]
TF-IDF doesn't handle negative ratings. this is fine
